name: Deploy to Production

on:
  push:
    branches: [ main ]  # или master, в зависимости от вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 185.255.120.50 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@185.255.120.50 "/opt/deploy-scripts/deploy.sh"
